// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_PRUEBA_1.Models;

public partial class Curso
{
    [Key]
    public int IdCurso { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string NombreCurso { get; set; }
    [Required]
    public int Horas { get; set; }
    [Required]
    public DateOnly FechaInicio { get; set; }

    [ForeignKey("IdCurso")]
    [InverseProperty("IdCursos")] //si genera conflicto con la definición del DbContext => eliminar
    public virtual ICollection<Empleado> IdEmpleados { get; set; } = new List<Empleado>();
}