// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APP_PRUEBA_1.Models;

[Index("Dni", Name = "UQ__Empleado__C035B8DDFA0A98A2", IsUnique = true)]
public partial class Empleado
{
    [Key]
    public int IdEmpleado { get; set; }

    [Column("DNI")]
    [Range(1, 70000000, ErrorMessage = "El valor del DNI debe estar entre 1 y 70.000.000")]
    public int Dni { get; set; }
    [Required]
    public bool Estado { get; set; }

    [Required]
    [StringLength(80)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(80)]
    [Unicode(false)]
    public string Apellido { get; set; }

    public DateOnly? FechaIngreso { get; set; }
    [Required]
    public int CantidadHijos { get; set; }
    [Required]
    public int IdDepartamento { get; set; }

    [ForeignKey("IdDepartamento")]
    [InverseProperty("Empleados")]
    public virtual Departamento IdDepartamentoNavigation { get; set; }

    [ForeignKey("IdEmpleado")]
    [InverseProperty("IdEmpleados")] //si genera conflicto con la definición del DbContext => eliminar
    public virtual ICollection<Curso> IdCursos { get; set; } = new List<Curso>();
}