// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace APP_PRUEBA_1.Models;

public partial class RRHH2026_Db_Context : DbContext
{
    public RRHH2026_Db_Context(DbContextOptions<RRHH2026_Db_Context> options)
        : base(options)
    {
    }
    public virtual DbSet<Curso> Cursos { get; set; }
    public virtual DbSet<Departamento> Departamentos { get; set; }
    public virtual DbSet<Empleado> Empleados { get; set; }
    public virtual DbSet<Usuario> Usuarios { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Curso>(entity =>
        {
            entity.HasKey(e => e.IdCurso).HasName("PK__Cursos__085F27D6C2463A61");

            entity.HasMany(d => d.IdEmpleados).WithMany(p => p.IdCursos)
                .UsingEntity<Dictionary<string, object>>(
                    "EmpleadoCurso",
                    r => r.HasOne<Empleado>().WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__EmpleadoC__IdEmp__412EB0B6"),
                    l => l.HasOne<Curso>().WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__EmpleadoC__IdCur__403A8C7D"),
                    j =>
                    {
                        j.HasKey("IdCurso", "IdEmpleado").HasName("PK__Empleado__F4B9FF6FDEE44C44");
                        j.ToTable("EmpleadoCurso");
                    });
        });

        modelBuilder.Entity<Departamento>(entity =>
        {
            entity.HasKey(e => e.IdDepartamento).HasName("PK__Departam__787A433DD5FFB417");
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.IdEmpleado).HasName("PK__Empleado__CE6D8B9E91B3E707");

            entity.Property(e => e.FechaIngreso).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdDepartamentoNavigation).WithMany(p => p.Empleados)
                .OnDelete(DeleteBehavior.Restrict)
                .HasConstraintName("FK_IdDepartamento");
        });

        modelBuilder.Entity<Usuario>(entity => 
        {
            entity.HasKey(e => e.IdUsuario);
            entity.Property(e => e.IdUsuario).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}